---
# This is the internal user database
_meta:
  type: "internalusers"
  config_version: 2

admin:
  hash: "changeme"
  reserved: true
  backend_roles:
    - "admin"
  description: "Demo admin user"

kibanaserver:
  hash: "changeme"
  reserved: true
  description: "Demo kibanaserver user"

kibanaro:
  hash: "changeme"
  reserved: false
  backend_roles:
    - "kibanauser"
    - "readall"
  attributes:
    attribute1: "value1"
    attribute2: "value2"
    attribute3: "value3"
  description: "Demo kibanaro user"

logstash:
  hash: "changeme"
  reserved: false
  backend_roles:
    - "logstash"
  description: "Demo logstash user"

readall:
  hash: "changeme"
  reserved: false
  backend_roles:
    - "readall"
  description: "Demo readall user"

snapshotrestore:
  hash: "changeme"
  reserved: false
  backend_roles:
    - "snapshotrestore"
  description: "Demo snapshotrestore user"

wazuh_admin:
  hash: "changeme"
  reserved: true
  hidden: false
  backend_roles: []
  attributes: {}
  opendistro_security_roles: []
  static: false

wazuh_user:
  hash: "changeme"
  reserved: true
  hidden: false
  backend_roles: []
  attributes: {}
  opendistro_security_roles: []
  static: false
