nodes:
  # Wazuh indexer server nodes
  indexer:
    - name: wazuh.indexer
      ip: 127.0.0.1

  # Wazuh server nodes
  # Use node_type only with more than one Wazuh manager
  server:
    - name: wazuh.manager
      ip: 127.0.0.1

  # Wazuh dashboard node
  dashboard:
    - name: wazuh.dashboard
      ip: 127.0.0.1
